[[plugins]]
repo = 'akinsho/toggleterm.nvim'
rev = 'v2.7.1'
hook_add = 'source ~/.local/share/dein/plugins/toggleterm.lua'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
rev = 'v3.5.1'
hook_add = 'source ~/.local/share/dein/plugins/nightfox.vim'

[[plugins]]
repo = 'github/copilot.vim'
rev = 'v1.9.1'
hook_add = 'source ~/.local/share/dein/plugins/copilot.vim'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
rev = 'v1.0.0'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = 'source ~/.local/share/dein/plugins/gitsigns.lua'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source ~/.local/share/dein/plugins/startify.vim'

[[plugins]]
repo = 'nanozuki/tabby.nvim'
rev = 'v2.1.5'
hook_add = 'source ~/.local/share/dein/plugins/tabby.lua'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
rev = 'v0.1.6'
hook_add = 'source ~/.local/share/dein/plugins/lspconfig.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.local/share/dein/plugins/lualine.lua'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'ojroques/nvim-osc52'
hook_add = 'source ~/.local/share/dein/plugins/osc52.lua'

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
hook_add = 'source ~/.local/share/dein/plugins/scrollbar.lua'

[[plugins]]
repo = 'vim-denops/denops.vim'
rev = 'v5.0.0'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
#hook_add = 'source ~/.local/share/dein/plugins/coc-vim.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'
hook_add = "au BufRead , BufNewFile *. sbt set filetype = scala"

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.local/share/dein/plugins/indentLine.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


